<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- saved from url=(0057)https://root.cern.ch/doc/master/TCanvasImp_8h_source.html -->
<html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

<meta http-equiv="X-UA-Compatible" content="IE=9">
<meta name="generator" content="Doxygen 1.8.9">
<title>ROOT: core/base/inc/TCanvasImp.h Source File</title>
<link href="./TCanvasImp_files/tabs.css" rel="stylesheet" type="text/css">
<script type="text/javascript" src="./TCanvasImp_files/jquery.js.download"></script>
<script type="text/javascript" src="./TCanvasImp_files/dynsections.js.download"></script>
<link href="./TCanvasImp_files/search.css" rel="stylesheet" type="text/css">
<script type="text/javascript" src="./TCanvasImp_files/searchdata.js.download"></script>
<script type="text/javascript" src="./TCanvasImp_files/search.js.download"></script>
<script type="text/javascript">
  $(document).ready(function() { init_search(); });
</script>
<script type="text/x-mathjax-config;executed=true">
  MathJax.Hub.Config({
    extensions: ["tex2jax.js"],
    jax: ["input/TeX","output/HTML-CSS"],
});
</script><script src="./TCanvasImp_files/MathJax.js.download"></script><style type="text/css">.MathJax_Preview {color: #888}
#MathJax_Message {position: fixed; left: 1em; bottom: 1.5em; background-color: #E6E6E6; border: 1px solid #959595; margin: 0px; padding: 2px 8px; z-index: 102; color: black; font-size: 80%; width: auto; white-space: nowrap}
#MathJax_MSIE_Frame {position: absolute; top: 0; left: 0; width: 0px; z-index: 101; border: 0px; margin: 0px; padding: 0px}
.MathJax_Error {color: #CC0000; font-style: italic}
</style>
<link href="./TCanvasImp_files/doxygen.css" rel="stylesheet" type="text/css">
<link href="./TCanvasImp_files/ROOT.css" rel="stylesheet" type="text/css">
<style type="text/css">#MathJax_About {position: fixed; left: 50%; width: auto; text-align: center; border: 3px outset; padding: 1em 2em; background-color: #DDDDDD; color: black; cursor: default; font-family: message-box; font-size: 120%; font-style: normal; text-indent: 0; text-transform: none; line-height: normal; letter-spacing: normal; word-spacing: normal; word-wrap: normal; white-space: nowrap; float: none; z-index: 201; border-radius: 15px; -webkit-border-radius: 15px; -moz-border-radius: 15px; -khtml-border-radius: 15px; box-shadow: 0px 10px 20px #808080; -webkit-box-shadow: 0px 10px 20px #808080; -moz-box-shadow: 0px 10px 20px #808080; -khtml-box-shadow: 0px 10px 20px #808080; filter: progid:DXImageTransform.Microsoft.dropshadow(OffX=2, OffY=2, Color='gray', Positive='true')}
#MathJax_About.MathJax_MousePost {outline: none}
.MathJax_Menu {position: absolute; background-color: white; color: black; width: auto; padding: 2px; border: 1px solid #CCCCCC; margin: 0; cursor: default; font: menu; text-align: left; text-indent: 0; text-transform: none; line-height: normal; letter-spacing: normal; word-spacing: normal; word-wrap: normal; white-space: nowrap; float: none; z-index: 201; box-shadow: 0px 10px 20px #808080; -webkit-box-shadow: 0px 10px 20px #808080; -moz-box-shadow: 0px 10px 20px #808080; -khtml-box-shadow: 0px 10px 20px #808080; filter: progid:DXImageTransform.Microsoft.dropshadow(OffX=2, OffY=2, Color='gray', Positive='true')}
.MathJax_MenuItem {padding: 2px 2em; background: transparent}
.MathJax_MenuArrow {position: absolute; right: .5em; padding-top: .25em; color: #666666; font-size: .75em}
.MathJax_MenuActive .MathJax_MenuArrow {color: white}
.MathJax_MenuArrow.RTL {left: .5em; right: auto}
.MathJax_MenuCheck {position: absolute; left: .7em}
.MathJax_MenuCheck.RTL {right: .7em; left: auto}
.MathJax_MenuRadioCheck {position: absolute; left: 1em}
.MathJax_MenuRadioCheck.RTL {right: 1em; left: auto}
.MathJax_MenuLabel {padding: 2px 2em 4px 1.33em; font-style: italic}
.MathJax_MenuRule {border-top: 1px solid #CCCCCC; margin: 4px 1px 0px}
.MathJax_MenuDisabled {color: GrayText}
.MathJax_MenuActive {background-color: Highlight; color: HighlightText}
.MathJax_MenuDisabled:focus, .MathJax_MenuLabel:focus {background-color: #E8E8E8}
.MathJax_ContextMenu:focus {outline: none}
.MathJax_ContextMenu .MathJax_MenuItem:focus {outline: none}
#MathJax_AboutClose {top: .2em; right: .2em}
.MathJax_Menu .MathJax_MenuClose {top: -10px; left: -10px}
.MathJax_MenuClose {position: absolute; cursor: pointer; display: inline-block; border: 2px solid #AAA; border-radius: 18px; -webkit-border-radius: 18px; -moz-border-radius: 18px; -khtml-border-radius: 18px; font-family: 'Courier New',Courier; font-size: 24px; color: #F0F0F0}
.MathJax_MenuClose span {display: block; background-color: #AAA; border: 1.5px solid; border-radius: 18px; -webkit-border-radius: 18px; -moz-border-radius: 18px; -khtml-border-radius: 18px; line-height: 0; padding: 8px 0 6px}
.MathJax_MenuClose:hover {color: white!important; border: 2px solid #CCC!important}
.MathJax_MenuClose:hover span {background-color: #CCC!important}
.MathJax_MenuClose:hover:focus {outline: none}
</style><style type="text/css">#MathJax_Zoom {position: absolute; background-color: #F0F0F0; overflow: auto; display: block; z-index: 301; padding: .5em; border: 1px solid black; margin: 0; font-weight: normal; font-style: normal; text-align: left; text-indent: 0; text-transform: none; line-height: normal; letter-spacing: normal; word-spacing: normal; word-wrap: normal; white-space: nowrap; float: none; -webkit-box-sizing: content-box; -moz-box-sizing: content-box; box-sizing: content-box; box-shadow: 5px 5px 15px #AAAAAA; -webkit-box-shadow: 5px 5px 15px #AAAAAA; -moz-box-shadow: 5px 5px 15px #AAAAAA; -khtml-box-shadow: 5px 5px 15px #AAAAAA; filter: progid:DXImageTransform.Microsoft.dropshadow(OffX=2, OffY=2, Color='gray', Positive='true')}
#MathJax_ZoomOverlay {position: absolute; left: 0; top: 0; z-index: 300; display: inline-block; width: 100%; height: 100%; border: 0; padding: 0; margin: 0; background-color: white; opacity: 0; filter: alpha(opacity=0)}
#MathJax_ZoomFrame {position: relative; display: inline-block; height: 0; width: 0}
#MathJax_ZoomEventTrap {position: absolute; left: 0; top: 0; z-index: 302; display: inline-block; border: 0; padding: 0; margin: 0; background-color: white; opacity: 0; filter: alpha(opacity=0)}
</style></head>
<body><div id="MathJax_Message" style="display: none;"></div>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table bgcolor="#346295" cellspacing="0" cellpadding="0">
  <tbody><tr>
    <td> <img style="height:90px" alt="Logo" src="./TCanvasImp_files/rootlogo.gif"> </td>
    <td valign="middle" style="color: #FFFFFF" nowrap="nowrap"><font size="6">ROOT</font> &nbsp; 6.09/03 <br> Reference Guide </td>
    <td style="width:100%"> </td>
  </tr>
</tbody></table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.9 -->
<script type="text/javascript">
var searchBox = new SearchBox("searchBox", "search",false,'Search');
</script>
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="http://root.cern.ch/"><span>ROOT&nbsp;Home&nbsp;Page</span></a></li>
      <li><a href="https://root.cern.ch/doc/master/index.html"><span>Main&nbsp;Page</span></a></li>
      <li><a href="https://root.cern.ch/doc/master/group__Tutorials.html"><span>Tutorials</span></a></li>
      <li><a href="https://root.cern.ch/doc/master/modules.html"><span>User's&nbsp;Classes</span></a></li>
      <li><a href="https://root.cern.ch/doc/master/namespaces.html"><span>Namespaces</span></a></li>
      <li><a href="https://root.cern.ch/doc/master/annotated.html"><span>All&nbsp;Classes</span></a></li>
      <li class="current"><a href="https://root.cern.ch/doc/master/files.html"><span>Files</span></a></li>
      <li><a href="https://root.cern.ch/doc/master/release-notes.html"><span>Release&nbsp;Notes</span></a></li>
      <li>
        <div id="MSearchBox" class="MSearchBoxInactive">
        <span class="left">
          <img id="MSearchSelect" src="./TCanvasImp_files/mag_sel.png" onmouseover="return searchBox.OnSearchSelectShow()" onmouseout="return searchBox.OnSearchSelectHide()" alt="">
          <input type="text" id="MSearchField" value="Search" accesskey="S" onfocus="searchBox.OnSearchFieldFocus(true)" onblur="searchBox.OnSearchFieldFocus(false)" onkeyup="searchBox.OnSearchFieldChange(event)">
          </span><span class="right">
            <a id="MSearchClose" href="javascript:searchBox.CloseResultsWindow()"><img id="MSearchCloseImg" border="0" src="./TCanvasImp_files/close.png" alt=""></a>
          </span>
        </div>
      </li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="https://root.cern.ch/doc/master/files.html"><span>File&nbsp;List</span></a></li>
      <li><a href="https://root.cern.ch/doc/master/globals.html"><span>File&nbsp;Members</span></a></li>
    </ul>
  </div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow" onmouseover="return searchBox.OnSearchSelectShow()" onmouseout="return searchBox.OnSearchSelectHide()" onkeydown="return searchBox.OnSearchSelectKey(event)">
<a class="SelectItem" onclick="searchBox.OnSelectItem(0)" href="javascript:void(0)"><span class="SelectionMark">•</span>All</a><a class="SelectItem" onclick="searchBox.OnSelectItem(1)" href="javascript:void(0)"><span class="SelectionMark">&nbsp;</span>Classes</a><a class="SelectItem" onclick="searchBox.OnSelectItem(2)" href="javascript:void(0)"><span class="SelectionMark">&nbsp;</span>Namespaces</a><a class="SelectItem" onclick="searchBox.OnSelectItem(3)" href="javascript:void(0)"><span class="SelectionMark">&nbsp;</span>Files</a><a class="SelectItem" onclick="searchBox.OnSelectItem(4)" href="javascript:void(0)"><span class="SelectionMark">&nbsp;</span>Functions</a><a class="SelectItem" onclick="searchBox.OnSelectItem(5)" href="javascript:void(0)"><span class="SelectionMark">&nbsp;</span>Variables</a><a class="SelectItem" onclick="searchBox.OnSelectItem(6)" href="javascript:void(0)"><span class="SelectionMark">&nbsp;</span>Typedefs</a><a class="SelectItem" onclick="searchBox.OnSelectItem(7)" href="javascript:void(0)"><span class="SelectionMark">&nbsp;</span>Enumerations</a><a class="SelectItem" onclick="searchBox.OnSelectItem(8)" href="javascript:void(0)"><span class="SelectionMark">&nbsp;</span>Enumerator</a><a class="SelectItem" onclick="searchBox.OnSelectItem(9)" href="javascript:void(0)"><span class="SelectionMark">&nbsp;</span>Properties</a><a class="SelectItem" onclick="searchBox.OnSelectItem(10)" href="javascript:void(0)"><span class="SelectionMark">&nbsp;</span>Friends</a><a class="SelectItem" onclick="searchBox.OnSelectItem(11)" href="javascript:void(0)"><span class="SelectionMark">&nbsp;</span>Macros</a><a class="SelectItem" onclick="searchBox.OnSelectItem(12)" href="javascript:void(0)"><span class="SelectionMark">&nbsp;</span>Modules</a><a class="SelectItem" onclick="searchBox.OnSelectItem(13)" href="javascript:void(0)"><span class="SelectionMark">&nbsp;</span>Pages</a></div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" name="MSearchResults" id="MSearchResults" src="./TCanvasImp_files/saved_resource.html">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="https://root.cern.ch/doc/master/dir_4270bfced15e0e73154b13468c7c9ad9.html">core</a></li><li class="navelem"><a class="el" href="https://root.cern.ch/doc/master/dir_b952992678633ce5ff96b3ca450b719d.html">base</a></li><li class="navelem"><a class="el" href="https://root.cern.ch/doc/master/dir_096f11663d5b0df5875ce3388f5709f9.html">inc</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">TCanvasImp.h</div>  </div>
</div><!--header-->
<div class="contents">
<a href="https://root.cern.ch/doc/master/TCanvasImp_8h.html">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&nbsp;<span class="comment">// @(#)root/base:$Id$</span></div>
<div class="line"><a name="l00002"></a><span class="lineno">    2</span>&nbsp;<span class="comment">// Author: Fons Rademakers   16/11/95</span></div>
<div class="line"><a name="l00003"></a><span class="lineno">    3</span>&nbsp;</div>
<div class="line"><a name="l00004"></a><span class="lineno">    4</span>&nbsp;<span class="comment">/*************************************************************************</span></div>
<div class="line"><a name="l00005"></a><span class="lineno">    5</span>&nbsp;<span class="comment"> * Copyright (C) 1995-2000, Rene Brun and Fons Rademakers.               *</span></div>
<div class="line"><a name="l00006"></a><span class="lineno">    6</span>&nbsp;<span class="comment"> * All rights reserved.                                                  *</span></div>
<div class="line"><a name="l00007"></a><span class="lineno">    7</span>&nbsp;<span class="comment"> *                                                                       *</span></div>
<div class="line"><a name="l00008"></a><span class="lineno">    8</span>&nbsp;<span class="comment"> * For the licensing terms see $ROOTSYS/LICENSE.                         *</span></div>
<div class="line"><a name="l00009"></a><span class="lineno">    9</span>&nbsp;<span class="comment"> * For the list of contributors see $ROOTSYS/README/CREDITS.             *</span></div>
<div class="line"><a name="l00010"></a><span class="lineno">   10</span>&nbsp;<span class="comment"> *************************************************************************/</span></div>
<div class="line"><a name="l00011"></a><span class="lineno">   11</span>&nbsp;</div>
<div class="line"><a name="l00012"></a><span class="lineno">   12</span>&nbsp;</div>
<div class="line"><a name="l00013"></a><span class="lineno">   13</span>&nbsp;<span class="preprocessor">#ifndef ROOT_TCanvasImp</span></div>
<div class="line"><a name="l00014"></a><span class="lineno">   14</span>&nbsp;<span class="preprocessor">#define ROOT_TCanvasImp</span></div>
<div class="line"><a name="l00015"></a><span class="lineno">   15</span>&nbsp;<span class="comment"></span></div>
<div class="line"><a name="l00016"></a><span class="lineno">   16</span>&nbsp;<span class="comment">//////////////////////////////////////////////////////////////////////////</span></div>
<div class="line"><a name="l00017"></a><span class="lineno">   17</span>&nbsp;<span class="comment"></span><span class="comment">//                                                                      //</span></div>
<div class="line"><a name="l00018"></a><span class="lineno">   18</span>&nbsp;<span class="comment">// TCanvasImp                                                           //</span></div>
<div class="line"><a name="l00019"></a><span class="lineno">   19</span>&nbsp;<span class="comment">//                                                                      //</span></div>
<div class="line"><a name="l00020"></a><span class="lineno">   20</span>&nbsp;<span class="comment">// ABC describing GUI independent main window (with menubar, scrollbars //</span></div>
<div class="line"><a name="l00021"></a><span class="lineno">   21</span>&nbsp;<span class="comment">// and a drawing area).                                                 //</span></div>
<div class="line"><a name="l00022"></a><span class="lineno">   22</span>&nbsp;<span class="comment">//                                                                      //</span><span class="comment"></span></div>
<div class="line"><a name="l00023"></a><span class="lineno">   23</span>&nbsp;<span class="comment">//////////////////////////////////////////////////////////////////////////</span></div>
<div class="line"><a name="l00024"></a><span class="lineno">   24</span>&nbsp;<span class="comment"></span></div>
<div class="line"><a name="l00025"></a><span class="lineno">   25</span>&nbsp;<span class="preprocessor">#include "<a class="code" href="https://root.cern.ch/doc/master/Rtypes_8h.html">Rtypes.h</a>"</span></div>
<div class="line"><a name="l00026"></a><span class="lineno">   26</span>&nbsp;</div>
<div class="line"><a name="l00027"></a><span class="lineno">   27</span>&nbsp;<span class="keyword">class </span><a class="code" href="https://root.cern.ch/doc/master/classTCanvas.html">TCanvas</a>;</div>
<div class="line"><a name="l00028"></a><span class="lineno">   28</span>&nbsp;</div>
<div class="line"><a name="l00029"></a><span class="lineno">   29</span>&nbsp;</div>
<div class="line"><a name="l00030"></a><span class="lineno"><a class="line" href="https://root.cern.ch/doc/master/classTCanvasImp.html">   30</a></span>&nbsp;<span class="keyword">class </span><a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html">TCanvasImp</a> {</div>
<div class="line"><a name="l00031"></a><span class="lineno"><a class="line" href="https://root.cern.ch/doc/master/classTCanvasImp.html#ac27c90fe0f7f3963df82036a5df8c6ee">   31</a></span>&nbsp;<span class="keyword">friend</span> <span class="keyword">class </span><a class="code" href="https://root.cern.ch/doc/master/classTCanvas.html">TCanvas</a>;</div>
<div class="line"><a name="l00032"></a><span class="lineno">   32</span>&nbsp;</div>
<div class="line"><a name="l00033"></a><span class="lineno">   33</span>&nbsp;<span class="keyword">protected</span>:</div>
<div class="line"><a name="l00034"></a><span class="lineno"><a class="line" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a32c6c0fc7ae4c49366ecfbed6da59d09">   34</a></span>&nbsp;   <a class="code" href="https://root.cern.ch/doc/master/classTCanvas.html">TCanvas</a>  *<a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a32c6c0fc7ae4c49366ecfbed6da59d09">fCanvas</a>;   <span class="comment">//TCanvas associated with this implementation</span></div>
<div class="line"><a name="l00035"></a><span class="lineno">   35</span>&nbsp;</div>
<div class="line"><a name="l00036"></a><span class="lineno"><a class="line" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a68169dfbff4fb6c3d29cc660961ac036">   36</a></span>&nbsp;   <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a68169dfbff4fb6c3d29cc660961ac036">TCanvasImp</a>(<span class="keyword">const</span> <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html">TCanvasImp</a>&amp; ci)</div>
<div class="line"><a name="l00037"></a><span class="lineno">   37</span>&nbsp;     : fCanvas(ci.fCanvas) { }</div>
<div class="line"><a name="l00038"></a><span class="lineno"><a class="line" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a878a4133409344e070bcc37e1d8fbdee">   38</a></span>&nbsp;   <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html">TCanvasImp</a>&amp; <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a878a4133409344e070bcc37e1d8fbdee">operator=</a>(<span class="keyword">const</span> <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html">TCanvasImp</a>&amp; ci)</div>
<div class="line"><a name="l00039"></a><span class="lineno">   39</span>&nbsp;     {<span class="keywordflow">if</span>(<span class="keyword">this</span>!=&amp;ci) fCanvas=ci.<a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a32c6c0fc7ae4c49366ecfbed6da59d09">fCanvas</a>; <span class="keywordflow">return</span> *<span class="keyword">this</span>;}</div>
<div class="line"><a name="l00040"></a><span class="lineno">   40</span>&nbsp;</div>
<div class="line"><a name="l00041"></a><span class="lineno"><a class="line" href="https://root.cern.ch/doc/master/classTCanvasImp.html#af723c8c3eac62d92e8ba34bac80c24a9">   41</a></span>&nbsp;   <span class="keyword">virtual</span> <span class="keywordtype">void</span>   <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#af723c8c3eac62d92e8ba34bac80c24a9">Lock</a>() { }</div>
<div class="line"><a name="l00042"></a><span class="lineno"><a class="line" href="https://root.cern.ch/doc/master/classTCanvasImp.html#aeb3e910019a0edc2fc127b70288095b0">   42</a></span>&nbsp;   <span class="keyword">virtual</span> <span class="keywordtype">void</span>   <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#aeb3e910019a0edc2fc127b70288095b0">Unlock</a>() { }</div>
<div class="line"><a name="l00043"></a><span class="lineno"><a class="line" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a80a4b394a2f100daa72e67a28bd00aed">   43</a></span>&nbsp;   <span class="keyword">virtual</span> <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#aa101f564ac7b845ca31aec2fbc00ce97">Bool_t</a> <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a80a4b394a2f100daa72e67a28bd00aed">IsLocked</a>() { <span class="keywordflow">return</span> <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a7e568baf910535e8ffd438acb843434d">kFALSE</a>; }</div>
<div class="line"><a name="l00044"></a><span class="lineno">   44</span>&nbsp;</div>
<div class="line"><a name="l00045"></a><span class="lineno">   45</span>&nbsp;<span class="keyword">public</span>:</div>
<div class="line"><a name="l00046"></a><span class="lineno"><a class="line" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a2c006ffd84056bd8f263429c6a666c6b">   46</a></span>&nbsp;   <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a2c006ffd84056bd8f263429c6a666c6b">TCanvasImp</a>(<a class="code" href="https://root.cern.ch/doc/master/classTCanvas.html">TCanvas</a> *c=0) : fCanvas(c) { }</div>
<div class="line"><a name="l00047"></a><span class="lineno">   47</span>&nbsp;   <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a68169dfbff4fb6c3d29cc660961ac036">TCanvasImp</a>(<a class="code" href="https://root.cern.ch/doc/master/classTCanvas.html">TCanvas</a> *c, <span class="keyword">const</span> <span class="keywordtype">char</span> *<a class="code" href="https://root.cern.ch/doc/master/TGX11_8cxx.html#a3777dbae63a15da001b2baa317a25149">name</a>, <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a7c1bc4939263cb6c0f48e434d77ac258">UInt_t</a> width, <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a7c1bc4939263cb6c0f48e434d77ac258">UInt_t</a> height);</div>
<div class="line"><a name="l00048"></a><span class="lineno">   48</span>&nbsp;   <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a68169dfbff4fb6c3d29cc660961ac036">TCanvasImp</a>(<a class="code" href="https://root.cern.ch/doc/master/classTCanvas.html">TCanvas</a> *c, <span class="keyword">const</span> <span class="keywordtype">char</span> *<a class="code" href="https://root.cern.ch/doc/master/TGX11_8cxx.html#a3777dbae63a15da001b2baa317a25149">name</a>, <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a3885b911a54b47a4e61671f45dd45d0b">Int_t</a> <a class="code" href="https://root.cern.ch/doc/master/legend1_8C.html#a13c6713ae496caa8195647f76887f926">x</a>, <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a3885b911a54b47a4e61671f45dd45d0b">Int_t</a> <a class="code" href="https://root.cern.ch/doc/master/legend1_8C.html#a1380cd153a0fc78015dd604dbcb6c841">y</a>, <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a7c1bc4939263cb6c0f48e434d77ac258">UInt_t</a> width, <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a7c1bc4939263cb6c0f48e434d77ac258">UInt_t</a> height);</div>
<div class="line"><a name="l00049"></a><span class="lineno"><a class="line" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a51292b8e008acf04f882817c8ab7d779">   49</a></span>&nbsp;   <span class="keyword">virtual</span> <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a51292b8e008acf04f882817c8ab7d779">~TCanvasImp</a>() { }</div>
<div class="line"><a name="l00050"></a><span class="lineno">   50</span>&nbsp;</div>
<div class="line"><a name="l00051"></a><span class="lineno"><a class="line" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a157ea763c5be29aeafd628cc8546c84a">   51</a></span>&nbsp;   <a class="code" href="https://root.cern.ch/doc/master/classTCanvas.html">TCanvas</a>       *<a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a157ea763c5be29aeafd628cc8546c84a">Canvas</a>()<span class="keyword"> const </span>{ <span class="keywordflow">return</span> <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a32c6c0fc7ae4c49366ecfbed6da59d09">fCanvas</a>; }</div>
<div class="line"><a name="l00052"></a><span class="lineno"><a class="line" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a5b889a910e3af7b228602bd733cc6eb3">   52</a></span>&nbsp;   <span class="keyword">virtual</span> <span class="keywordtype">void</span>   <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a5b889a910e3af7b228602bd733cc6eb3">Close</a>() { }</div>
<div class="line"><a name="l00053"></a><span class="lineno"><a class="line" href="https://root.cern.ch/doc/master/classTCanvasImp.html#add4bb48191350eb01d1def0ef0de22a1">   53</a></span>&nbsp;   <span class="keyword">virtual</span> <span class="keywordtype">void</span>   <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#add4bb48191350eb01d1def0ef0de22a1">ForceUpdate</a>() { }</div>
<div class="line"><a name="l00054"></a><span class="lineno">   54</span>&nbsp;   <span class="keyword">virtual</span> <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a7c1bc4939263cb6c0f48e434d77ac258">UInt_t</a> <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#ac7594eb595fe594d57468cfe441d3d78">GetWindowGeometry</a>(<a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a3885b911a54b47a4e61671f45dd45d0b">Int_t</a> &amp;<a class="code" href="https://root.cern.ch/doc/master/legend1_8C.html#a13c6713ae496caa8195647f76887f926">x</a>, <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a3885b911a54b47a4e61671f45dd45d0b">Int_t</a> &amp;<a class="code" href="https://root.cern.ch/doc/master/legend1_8C.html#a1380cd153a0fc78015dd604dbcb6c841">y</a>, <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a7c1bc4939263cb6c0f48e434d77ac258">UInt_t</a> &amp;w, <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a7c1bc4939263cb6c0f48e434d77ac258">UInt_t</a> &amp;<a class="code" href="https://root.cern.ch/doc/master/legend2_8C.html#aff0c8c7466e67c85c93218f48b4690f2">h</a>);</div>
<div class="line"><a name="l00055"></a><span class="lineno"><a class="line" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a2f839d49686cd9ad96865ea2f8a0f28f">   55</a></span>&nbsp;   <span class="keyword">virtual</span> <span class="keywordtype">void</span>   <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a2f839d49686cd9ad96865ea2f8a0f28f">Iconify</a>() { }</div>
<div class="line"><a name="l00056"></a><span class="lineno"><a class="line" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a3659d33f45cf47172045da9627c4cb3c">   56</a></span>&nbsp;   <span class="keyword">virtual</span> <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a3885b911a54b47a4e61671f45dd45d0b">Int_t</a>  <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a3659d33f45cf47172045da9627c4cb3c">InitWindow</a>() { <span class="keywordflow">return</span> 0; }</div>
<div class="line"><a name="l00057"></a><span class="lineno">   57</span>&nbsp;   <span class="keyword">virtual</span> <span class="keywordtype">void</span>   <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#ac6386a8dbe6a6abee94275219a01d30f">SetStatusText</a>(<span class="keyword">const</span> <span class="keywordtype">char</span> *<a class="code" href="https://root.cern.ch/doc/master/entrylist__figure1_8C.html#af575f17e6be3f269b86b041a60560dbf">text</a> = 0, <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a3885b911a54b47a4e61671f45dd45d0b">Int_t</a> partidx = 0);</div>
<div class="line"><a name="l00058"></a><span class="lineno">   58</span>&nbsp;   <span class="keyword">virtual</span> <span class="keywordtype">void</span>   <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a5dedbf6d715572f35aa2835edaff8de6">SetWindowPosition</a>(<a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a3885b911a54b47a4e61671f45dd45d0b">Int_t</a> <a class="code" href="https://root.cern.ch/doc/master/legend1_8C.html#a13c6713ae496caa8195647f76887f926">x</a>, <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a3885b911a54b47a4e61671f45dd45d0b">Int_t</a> <a class="code" href="https://root.cern.ch/doc/master/legend1_8C.html#a1380cd153a0fc78015dd604dbcb6c841">y</a>);</div>
<div class="line"><a name="l00059"></a><span class="lineno">   59</span>&nbsp;   <span class="keyword">virtual</span> <span class="keywordtype">void</span>   <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#aabffe435f4b676787a72c94b789e0171">SetWindowSize</a>(<a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a7c1bc4939263cb6c0f48e434d77ac258">UInt_t</a> w, <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a7c1bc4939263cb6c0f48e434d77ac258">UInt_t</a> <a class="code" href="https://root.cern.ch/doc/master/legend2_8C.html#aff0c8c7466e67c85c93218f48b4690f2">h</a>);</div>
<div class="line"><a name="l00060"></a><span class="lineno">   60</span>&nbsp;   <span class="keyword">virtual</span> <span class="keywordtype">void</span>   <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a66772366269366beeb6ffb5c10f8ebec">SetWindowTitle</a>(<span class="keyword">const</span> <span class="keywordtype">char</span> *newTitle);</div>
<div class="line"><a name="l00061"></a><span class="lineno">   61</span>&nbsp;   <span class="keyword">virtual</span> <span class="keywordtype">void</span>   <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#af79532f07f04b051aca8be6f3f08a096">SetCanvasSize</a>(<a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a7c1bc4939263cb6c0f48e434d77ac258">UInt_t</a> w, <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a7c1bc4939263cb6c0f48e434d77ac258">UInt_t</a> <a class="code" href="https://root.cern.ch/doc/master/legend2_8C.html#aff0c8c7466e67c85c93218f48b4690f2">h</a>);</div>
<div class="line"><a name="l00062"></a><span class="lineno"><a class="line" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a1e6d1a9263b8e53aa7ca411aa51b8a12">   62</a></span>&nbsp;   <span class="keyword">virtual</span> <span class="keywordtype">void</span>   <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a1e6d1a9263b8e53aa7ca411aa51b8a12">Show</a>() { }</div>
<div class="line"><a name="l00063"></a><span class="lineno">   63</span>&nbsp;   <span class="keyword">virtual</span> <span class="keywordtype">void</span>   <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#aa4b811931315b7f4852f0462ed9f9b88">ShowMenuBar</a>(<a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#aa101f564ac7b845ca31aec2fbc00ce97">Bool_t</a> show = <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#af2f51d30ccd86e85be3e3e69793a86ef">kTRUE</a>);</div>
<div class="line"><a name="l00064"></a><span class="lineno">   64</span>&nbsp;   <span class="keyword">virtual</span> <span class="keywordtype">void</span>   <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#aaf6cd381c82450b274bc1f128a30e42d">ShowStatusBar</a>(<a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#aa101f564ac7b845ca31aec2fbc00ce97">Bool_t</a> show = <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#af2f51d30ccd86e85be3e3e69793a86ef">kTRUE</a>);</div>
<div class="line"><a name="l00065"></a><span class="lineno">   65</span>&nbsp;   <span class="keyword">virtual</span> <span class="keywordtype">void</span>   <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a98df840683a4410e3affeca593dd4411">RaiseWindow</a>();</div>
<div class="line"><a name="l00066"></a><span class="lineno">   66</span>&nbsp;   <span class="keyword">virtual</span> <span class="keywordtype">void</span>   <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#acdbf048354cd185438d549a8a5544b08">ReallyDelete</a>();</div>
<div class="line"><a name="l00067"></a><span class="lineno">   67</span>&nbsp;</div>
<div class="line"><a name="l00068"></a><span class="lineno">   68</span>&nbsp;   <span class="keyword">virtual</span> <span class="keywordtype">void</span>   <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#aa50552745a11eb2c8fac21ffa34d8706">ShowEditor</a>(<a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#aa101f564ac7b845ca31aec2fbc00ce97">Bool_t</a> show = <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#af2f51d30ccd86e85be3e3e69793a86ef">kTRUE</a>);</div>
<div class="line"><a name="l00069"></a><span class="lineno">   69</span>&nbsp;   <span class="keyword">virtual</span> <span class="keywordtype">void</span>   <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a89803b1f8f70ecc23401ab64724e35a0">ShowToolBar</a>(<a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#aa101f564ac7b845ca31aec2fbc00ce97">Bool_t</a> show = <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#af2f51d30ccd86e85be3e3e69793a86ef">kTRUE</a>);</div>
<div class="line"><a name="l00070"></a><span class="lineno">   70</span>&nbsp;   <span class="keyword">virtual</span> <span class="keywordtype">void</span>   <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#ac486d4cbf5a0e8579e789ff674b8c17c">ShowToolTips</a>(<a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#aa101f564ac7b845ca31aec2fbc00ce97">Bool_t</a> show = <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#af2f51d30ccd86e85be3e3e69793a86ef">kTRUE</a>);</div>
<div class="line"><a name="l00071"></a><span class="lineno">   71</span>&nbsp;</div>
<div class="line"><a name="l00072"></a><span class="lineno"><a class="line" href="https://root.cern.ch/doc/master/classTCanvasImp.html#ac1b23830fcf1e1835d3fb4a8fd14a7fa">   72</a></span>&nbsp;   <span class="keyword">virtual</span> <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#aa101f564ac7b845ca31aec2fbc00ce97">Bool_t</a> <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#ac1b23830fcf1e1835d3fb4a8fd14a7fa">HasEditor</a>()<span class="keyword"> const </span>{ <span class="keywordflow">return</span> <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a7e568baf910535e8ffd438acb843434d">kFALSE</a>; }</div>
<div class="line"><a name="l00073"></a><span class="lineno"><a class="line" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a2c2d1a98a7573ec72056f3a18d4ad637">   73</a></span>&nbsp;   <span class="keyword">virtual</span> <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#aa101f564ac7b845ca31aec2fbc00ce97">Bool_t</a> <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a2c2d1a98a7573ec72056f3a18d4ad637">HasMenuBar</a>()<span class="keyword"> const </span>{ <span class="keywordflow">return</span> <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a7e568baf910535e8ffd438acb843434d">kFALSE</a>; }</div>
<div class="line"><a name="l00074"></a><span class="lineno"><a class="line" href="https://root.cern.ch/doc/master/classTCanvasImp.html#ad136e73ba0b1a250466c32ce2f4cd176">   74</a></span>&nbsp;   <span class="keyword">virtual</span> <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#aa101f564ac7b845ca31aec2fbc00ce97">Bool_t</a> <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#ad136e73ba0b1a250466c32ce2f4cd176">HasStatusBar</a>()<span class="keyword"> const </span>{ <span class="keywordflow">return</span> <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a7e568baf910535e8ffd438acb843434d">kFALSE</a>; }</div>
<div class="line"><a name="l00075"></a><span class="lineno"><a class="line" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a94259ec6635a0c19cdf5575ee81fc80e">   75</a></span>&nbsp;   <span class="keyword">virtual</span> <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#aa101f564ac7b845ca31aec2fbc00ce97">Bool_t</a> <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a94259ec6635a0c19cdf5575ee81fc80e">HasToolBar</a>()<span class="keyword"> const </span>{ <span class="keywordflow">return</span> <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a7e568baf910535e8ffd438acb843434d">kFALSE</a>; }</div>
<div class="line"><a name="l00076"></a><span class="lineno"><a class="line" href="https://root.cern.ch/doc/master/classTCanvasImp.html#aa7f976328703bf884f05e2e4698c1eac">   76</a></span>&nbsp;   <span class="keyword">virtual</span> <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#aa101f564ac7b845ca31aec2fbc00ce97">Bool_t</a> <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#aa7f976328703bf884f05e2e4698c1eac">HasToolTips</a>()<span class="keyword"> const </span>{ <span class="keywordflow">return</span> <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a7e568baf910535e8ffd438acb843434d">kFALSE</a>; }</div>
<div class="line"><a name="l00077"></a><span class="lineno">   77</span>&nbsp;</div>
<div class="line"><a name="l00078"></a><span class="lineno">   78</span>&nbsp;   <a class="code" href="https://root.cern.ch/doc/master/Rtypes_8h.html#a0f5f4feb8484fa7bec8adf82b6c3836b">ClassDef</a>(<a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html">TCanvasImp</a>,0)  <span class="comment">//ABC describing main window protocol</span></div>
<div class="line"><a name="l00079"></a><span class="lineno">   79</span>&nbsp;};</div>
<div class="line"><a name="l00080"></a><span class="lineno">   80</span>&nbsp;</div>
<div class="line"><a name="l00081"></a><span class="lineno"><a class="line" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a57b078381008982e8489d9c60d9cef78">   81</a></span>&nbsp;<span class="keyword">inline</span> <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a68169dfbff4fb6c3d29cc660961ac036">TCanvasImp::TCanvasImp</a>(<a class="code" href="https://root.cern.ch/doc/master/classTCanvas.html">TCanvas</a> *c, <span class="keyword">const</span> <span class="keywordtype">char</span> *, <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a7c1bc4939263cb6c0f48e434d77ac258">UInt_t</a>, <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a7c1bc4939263cb6c0f48e434d77ac258">UInt_t</a>) : <a class="code" href="https://root.cern.ch/doc/master/classTPad.html#a80aeefac6f7ee8ab3912945a51dd353f">fCanvas</a>(c) { }</div>
<div class="line"><a name="l00082"></a><span class="lineno"><a class="line" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a40a451dccc498ebfeba958febf94c51b">   82</a></span>&nbsp;<span class="keyword">inline</span> <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a68169dfbff4fb6c3d29cc660961ac036">TCanvasImp::TCanvasImp</a>(<a class="code" href="https://root.cern.ch/doc/master/classTCanvas.html">TCanvas</a> *c, <span class="keyword">const</span> <span class="keywordtype">char</span> *, <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a3885b911a54b47a4e61671f45dd45d0b">Int_t</a>, <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a3885b911a54b47a4e61671f45dd45d0b">Int_t</a>, <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a7c1bc4939263cb6c0f48e434d77ac258">UInt_t</a>, <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a7c1bc4939263cb6c0f48e434d77ac258">UInt_t</a>) : <a class="code" href="https://root.cern.ch/doc/master/classTPad.html#a80aeefac6f7ee8ab3912945a51dd353f">fCanvas</a>(c) { }</div>
<div class="line"><a name="l00083"></a><span class="lineno"><a class="line" href="https://root.cern.ch/doc/master/classTCanvasImp.html#ac7594eb595fe594d57468cfe441d3d78">   83</a></span>&nbsp;<span class="keyword">inline</span> <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a7c1bc4939263cb6c0f48e434d77ac258">UInt_t</a> <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#ac7594eb595fe594d57468cfe441d3d78">TCanvasImp::GetWindowGeometry</a>(<a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a3885b911a54b47a4e61671f45dd45d0b">Int_t</a> &amp;<a class="code" href="https://root.cern.ch/doc/master/legend1_8C.html#a13c6713ae496caa8195647f76887f926">x</a>, <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a3885b911a54b47a4e61671f45dd45d0b">Int_t</a> &amp;<a class="code" href="https://root.cern.ch/doc/master/legend1_8C.html#a1380cd153a0fc78015dd604dbcb6c841">y</a>, <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a7c1bc4939263cb6c0f48e434d77ac258">UInt_t</a> &amp;w, <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a7c1bc4939263cb6c0f48e434d77ac258">UInt_t</a> &amp;<a class="code" href="https://root.cern.ch/doc/master/legend2_8C.html#aff0c8c7466e67c85c93218f48b4690f2">h</a>)</div>
<div class="line"><a name="l00084"></a><span class="lineno">   84</span>&nbsp;               { x = y = 0; w = h = 0; <span class="keywordflow">return</span> 0;}</div>
<div class="line"><a name="l00085"></a><span class="lineno"><a class="line" href="https://root.cern.ch/doc/master/classTCanvasImp.html#ac6386a8dbe6a6abee94275219a01d30f">   85</a></span>&nbsp;<span class="keyword">inline</span> <span class="keywordtype">void</span> <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#ac6386a8dbe6a6abee94275219a01d30f">TCanvasImp::SetStatusText</a>(<span class="keyword">const</span> <span class="keywordtype">char</span> *, <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a3885b911a54b47a4e61671f45dd45d0b">Int_t</a>) { }</div>
<div class="line"><a name="l00086"></a><span class="lineno"><a class="line" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a5dedbf6d715572f35aa2835edaff8de6">   86</a></span>&nbsp;<span class="keyword">inline</span> <span class="keywordtype">void</span> <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a5dedbf6d715572f35aa2835edaff8de6">TCanvasImp::SetWindowPosition</a>(<a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a3885b911a54b47a4e61671f45dd45d0b">Int_t</a>, <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a3885b911a54b47a4e61671f45dd45d0b">Int_t</a>) { }</div>
<div class="line"><a name="l00087"></a><span class="lineno"><a class="line" href="https://root.cern.ch/doc/master/classTCanvasImp.html#aabffe435f4b676787a72c94b789e0171">   87</a></span>&nbsp;<span class="keyword">inline</span> <span class="keywordtype">void</span> <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#aabffe435f4b676787a72c94b789e0171">TCanvasImp::SetWindowSize</a>(<a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a7c1bc4939263cb6c0f48e434d77ac258">UInt_t</a>, <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a7c1bc4939263cb6c0f48e434d77ac258">UInt_t</a>) { }</div>
<div class="line"><a name="l00088"></a><span class="lineno"><a class="line" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a66772366269366beeb6ffb5c10f8ebec">   88</a></span>&nbsp;<span class="keyword">inline</span> <span class="keywordtype">void</span> <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a66772366269366beeb6ffb5c10f8ebec">TCanvasImp::SetWindowTitle</a>(<span class="keyword">const</span> <span class="keywordtype">char</span> *) { }</div>
<div class="line"><a name="l00089"></a><span class="lineno"><a class="line" href="https://root.cern.ch/doc/master/classTCanvasImp.html#af79532f07f04b051aca8be6f3f08a096">   89</a></span>&nbsp;<span class="keyword">inline</span> <span class="keywordtype">void</span> <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#af79532f07f04b051aca8be6f3f08a096">TCanvasImp::SetCanvasSize</a>(<a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a7c1bc4939263cb6c0f48e434d77ac258">UInt_t</a>, <a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a7c1bc4939263cb6c0f48e434d77ac258">UInt_t</a>) { }</div>
<div class="line"><a name="l00090"></a><span class="lineno"><a class="line" href="https://root.cern.ch/doc/master/classTCanvasImp.html#aa4b811931315b7f4852f0462ed9f9b88">   90</a></span>&nbsp;<span class="keyword">inline</span> <span class="keywordtype">void</span> <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#aa4b811931315b7f4852f0462ed9f9b88">TCanvasImp::ShowMenuBar</a>(<a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#aa101f564ac7b845ca31aec2fbc00ce97">Bool_t</a>) { }</div>
<div class="line"><a name="l00091"></a><span class="lineno"><a class="line" href="https://root.cern.ch/doc/master/classTCanvasImp.html#aaf6cd381c82450b274bc1f128a30e42d">   91</a></span>&nbsp;<span class="keyword">inline</span> <span class="keywordtype">void</span> <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#aaf6cd381c82450b274bc1f128a30e42d">TCanvasImp::ShowStatusBar</a>(<a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#aa101f564ac7b845ca31aec2fbc00ce97">Bool_t</a>) { }</div>
<div class="line"><a name="l00092"></a><span class="lineno"><a class="line" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a98df840683a4410e3affeca593dd4411">   92</a></span>&nbsp;<span class="keyword">inline</span> <span class="keywordtype">void</span> <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a98df840683a4410e3affeca593dd4411">TCanvasImp::RaiseWindow</a>() { }</div>
<div class="line"><a name="l00093"></a><span class="lineno"><a class="line" href="https://root.cern.ch/doc/master/classTCanvasImp.html#acdbf048354cd185438d549a8a5544b08">   93</a></span>&nbsp;<span class="keyword">inline</span> <span class="keywordtype">void</span> <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#acdbf048354cd185438d549a8a5544b08">TCanvasImp::ReallyDelete</a>() { }</div>
<div class="line"><a name="l00094"></a><span class="lineno">   94</span>&nbsp;</div>
<div class="line"><a name="l00095"></a><span class="lineno"><a class="line" href="https://root.cern.ch/doc/master/classTCanvasImp.html#aa50552745a11eb2c8fac21ffa34d8706">   95</a></span>&nbsp;<span class="keyword">inline</span> <span class="keywordtype">void</span> <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#aa50552745a11eb2c8fac21ffa34d8706">TCanvasImp::ShowEditor</a>(<a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#aa101f564ac7b845ca31aec2fbc00ce97">Bool_t</a>) { }</div>
<div class="line"><a name="l00096"></a><span class="lineno"><a class="line" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a89803b1f8f70ecc23401ab64724e35a0">   96</a></span>&nbsp;<span class="keyword">inline</span> <span class="keywordtype">void</span> <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#a89803b1f8f70ecc23401ab64724e35a0">TCanvasImp::ShowToolBar</a>(<a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#aa101f564ac7b845ca31aec2fbc00ce97">Bool_t</a>) { }</div>
<div class="line"><a name="l00097"></a><span class="lineno"><a class="line" href="https://root.cern.ch/doc/master/classTCanvasImp.html#ac486d4cbf5a0e8579e789ff674b8c17c">   97</a></span>&nbsp;<span class="keyword">inline</span> <span class="keywordtype">void</span> <a class="code" href="https://root.cern.ch/doc/master/classTCanvasImp.html#ac486d4cbf5a0e8579e789ff674b8c17c">TCanvasImp::ShowToolTips</a>(<a class="code" href="https://root.cern.ch/doc/master/RtypesCore_8h.html#aa101f564ac7b845ca31aec2fbc00ce97">Bool_t</a>) { }</div>
<div class="line"><a name="l00098"></a><span class="lineno">   98</span>&nbsp;</div>
<div class="line"><a name="l00099"></a><span class="lineno">   99</span>&nbsp;<span class="preprocessor">#endif</span></div>
<div class="ttc" id="classTCanvasImp_html"><div class="ttname"><a href="https://root.cern.ch/doc/master/classTCanvasImp.html">TCanvasImp</a></div><div class="ttdoc">ABC describing GUI independent main window (with menubar, scrollbars and a drawing area)...</div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/TCanvasImp_8h_source.html#l00030">TCanvasImp.h:30</a></div></div>
<div class="ttc" id="classTCanvasImp_html_a878a4133409344e070bcc37e1d8fbdee"><div class="ttname"><a href="https://root.cern.ch/doc/master/classTCanvasImp.html#a878a4133409344e070bcc37e1d8fbdee">TCanvasImp::operator=</a></div><div class="ttdeci">TCanvasImp &amp; operator=(const TCanvasImp &amp;ci)</div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/TCanvasImp_8h_source.html#l00038">TCanvasImp.h:38</a></div></div>
<div class="ttc" id="classTCanvasImp_html_acdbf048354cd185438d549a8a5544b08"><div class="ttname"><a href="https://root.cern.ch/doc/master/classTCanvasImp.html#acdbf048354cd185438d549a8a5544b08">TCanvasImp::ReallyDelete</a></div><div class="ttdeci">virtual void ReallyDelete()</div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/TCanvasImp_8h_source.html#l00093">TCanvasImp.h:93</a></div></div>
<div class="ttc" id="Rtypes_8h_html"><div class="ttname"><a href="https://root.cern.ch/doc/master/Rtypes_8h.html">Rtypes.h</a></div></div>
<div class="ttc" id="classTCanvasImp_html_a94259ec6635a0c19cdf5575ee81fc80e"><div class="ttname"><a href="https://root.cern.ch/doc/master/classTCanvasImp.html#a94259ec6635a0c19cdf5575ee81fc80e">TCanvasImp::HasToolBar</a></div><div class="ttdeci">virtual Bool_t HasToolBar() const </div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/TCanvasImp_8h_source.html#l00075">TCanvasImp.h:75</a></div></div>
<div class="ttc" id="classTCanvasImp_html_a5dedbf6d715572f35aa2835edaff8de6"><div class="ttname"><a href="https://root.cern.ch/doc/master/classTCanvasImp.html#a5dedbf6d715572f35aa2835edaff8de6">TCanvasImp::SetWindowPosition</a></div><div class="ttdeci">virtual void SetWindowPosition(Int_t x, Int_t y)</div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/TCanvasImp_8h_source.html#l00086">TCanvasImp.h:86</a></div></div>
<div class="ttc" id="legend2_8C_html_aff0c8c7466e67c85c93218f48b4690f2"><div class="ttname"><a href="https://root.cern.ch/doc/master/legend2_8C.html#aff0c8c7466e67c85c93218f48b4690f2">h</a></div><div class="ttdeci">TH1 * h</div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/legend2_8C_source.html#l00005">legend2.C:5</a></div></div>
<div class="ttc" id="classTCanvasImp_html_a2c006ffd84056bd8f263429c6a666c6b"><div class="ttname"><a href="https://root.cern.ch/doc/master/classTCanvasImp.html#a2c006ffd84056bd8f263429c6a666c6b">TCanvasImp::TCanvasImp</a></div><div class="ttdeci">TCanvasImp(TCanvas *c=0)</div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/TCanvasImp_8h_source.html#l00046">TCanvasImp.h:46</a></div></div>
<div class="ttc" id="classTCanvasImp_html_a66772366269366beeb6ffb5c10f8ebec"><div class="ttname"><a href="https://root.cern.ch/doc/master/classTCanvasImp.html#a66772366269366beeb6ffb5c10f8ebec">TCanvasImp::SetWindowTitle</a></div><div class="ttdeci">virtual void SetWindowTitle(const char *newTitle)</div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/TCanvasImp_8h_source.html#l00088">TCanvasImp.h:88</a></div></div>
<div class="ttc" id="classTCanvasImp_html_ac1b23830fcf1e1835d3fb4a8fd14a7fa"><div class="ttname"><a href="https://root.cern.ch/doc/master/classTCanvasImp.html#ac1b23830fcf1e1835d3fb4a8fd14a7fa">TCanvasImp::HasEditor</a></div><div class="ttdeci">virtual Bool_t HasEditor() const </div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/TCanvasImp_8h_source.html#l00072">TCanvasImp.h:72</a></div></div>
<div class="ttc" id="classTCanvasImp_html_a68169dfbff4fb6c3d29cc660961ac036"><div class="ttname"><a href="https://root.cern.ch/doc/master/classTCanvasImp.html#a68169dfbff4fb6c3d29cc660961ac036">TCanvasImp::TCanvasImp</a></div><div class="ttdeci">TCanvasImp(const TCanvasImp &amp;ci)</div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/TCanvasImp_8h_source.html#l00036">TCanvasImp.h:36</a></div></div>
<div class="ttc" id="RtypesCore_8h_html_a3885b911a54b47a4e61671f45dd45d0b"><div class="ttname"><a href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a3885b911a54b47a4e61671f45dd45d0b">Int_t</a></div><div class="ttdeci">int Int_t</div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/RtypesCore_8h_source.html#l00041">RtypesCore.h:41</a></div></div>
<div class="ttc" id="RtypesCore_8h_html_aa101f564ac7b845ca31aec2fbc00ce97"><div class="ttname"><a href="https://root.cern.ch/doc/master/RtypesCore_8h.html#aa101f564ac7b845ca31aec2fbc00ce97">Bool_t</a></div><div class="ttdeci">bool Bool_t</div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/RtypesCore_8h_source.html#l00059">RtypesCore.h:59</a></div></div>
<div class="ttc" id="classTCanvasImp_html_a98df840683a4410e3affeca593dd4411"><div class="ttname"><a href="https://root.cern.ch/doc/master/classTCanvasImp.html#a98df840683a4410e3affeca593dd4411">TCanvasImp::RaiseWindow</a></div><div class="ttdeci">virtual void RaiseWindow()</div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/TCanvasImp_8h_source.html#l00092">TCanvasImp.h:92</a></div></div>
<div class="ttc" id="classTCanvasImp_html_a157ea763c5be29aeafd628cc8546c84a"><div class="ttname"><a href="https://root.cern.ch/doc/master/classTCanvasImp.html#a157ea763c5be29aeafd628cc8546c84a">TCanvasImp::Canvas</a></div><div class="ttdeci">TCanvas * Canvas() const </div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/TCanvasImp_8h_source.html#l00051">TCanvasImp.h:51</a></div></div>
<div class="ttc" id="classTCanvasImp_html_a80a4b394a2f100daa72e67a28bd00aed"><div class="ttname"><a href="https://root.cern.ch/doc/master/classTCanvasImp.html#a80a4b394a2f100daa72e67a28bd00aed">TCanvasImp::IsLocked</a></div><div class="ttdeci">virtual Bool_t IsLocked()</div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/TCanvasImp_8h_source.html#l00043">TCanvasImp.h:43</a></div></div>
<div class="ttc" id="legend1_8C_html_a13c6713ae496caa8195647f76887f926"><div class="ttname"><a href="https://root.cern.ch/doc/master/legend1_8C.html#a13c6713ae496caa8195647f76887f926">x</a></div><div class="ttdeci">Double_t x[n]</div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/legend1_8C_source.html#l00017">legend1.C:17</a></div></div>
<div class="ttc" id="classTCanvasImp_html_ad136e73ba0b1a250466c32ce2f4cd176"><div class="ttname"><a href="https://root.cern.ch/doc/master/classTCanvasImp.html#ad136e73ba0b1a250466c32ce2f4cd176">TCanvasImp::HasStatusBar</a></div><div class="ttdeci">virtual Bool_t HasStatusBar() const </div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/TCanvasImp_8h_source.html#l00074">TCanvasImp.h:74</a></div></div>
<div class="ttc" id="Rtypes_8h_html_a0f5f4feb8484fa7bec8adf82b6c3836b"><div class="ttname"><a href="https://root.cern.ch/doc/master/Rtypes_8h.html#a0f5f4feb8484fa7bec8adf82b6c3836b">ClassDef</a></div><div class="ttdeci">#define ClassDef(name, id)</div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/Rtypes_8h_source.html#l00297">Rtypes.h:297</a></div></div>
<div class="ttc" id="classTCanvasImp_html_aa50552745a11eb2c8fac21ffa34d8706"><div class="ttname"><a href="https://root.cern.ch/doc/master/classTCanvasImp.html#aa50552745a11eb2c8fac21ffa34d8706">TCanvasImp::ShowEditor</a></div><div class="ttdeci">virtual void ShowEditor(Bool_t show=kTRUE)</div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/TCanvasImp_8h_source.html#l00095">TCanvasImp.h:95</a></div></div>
<div class="ttc" id="classTCanvasImp_html_a1e6d1a9263b8e53aa7ca411aa51b8a12"><div class="ttname"><a href="https://root.cern.ch/doc/master/classTCanvasImp.html#a1e6d1a9263b8e53aa7ca411aa51b8a12">TCanvasImp::Show</a></div><div class="ttdeci">virtual void Show()</div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/TCanvasImp_8h_source.html#l00062">TCanvasImp.h:62</a></div></div>
<div class="ttc" id="classTPad_html_a80aeefac6f7ee8ab3912945a51dd353f"><div class="ttname"><a href="https://root.cern.ch/doc/master/classTPad.html#a80aeefac6f7ee8ab3912945a51dd353f">TPad::fCanvas</a></div><div class="ttdeci">TCanvas * fCanvas</div><div class="ttdoc">! Pointer to mother canvas </div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/TPad_8h_source.html#l00105">TPad.h:105</a></div></div>
<div class="ttc" id="classTCanvasImp_html_a5b889a910e3af7b228602bd733cc6eb3"><div class="ttname"><a href="https://root.cern.ch/doc/master/classTCanvasImp.html#a5b889a910e3af7b228602bd733cc6eb3">TCanvasImp::Close</a></div><div class="ttdeci">virtual void Close()</div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/TCanvasImp_8h_source.html#l00052">TCanvasImp.h:52</a></div></div>
<div class="ttc" id="classTCanvasImp_html_a89803b1f8f70ecc23401ab64724e35a0"><div class="ttname"><a href="https://root.cern.ch/doc/master/classTCanvasImp.html#a89803b1f8f70ecc23401ab64724e35a0">TCanvasImp::ShowToolBar</a></div><div class="ttdeci">virtual void ShowToolBar(Bool_t show=kTRUE)</div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/TCanvasImp_8h_source.html#l00096">TCanvasImp.h:96</a></div></div>
<div class="ttc" id="classTCanvasImp_html_aa4b811931315b7f4852f0462ed9f9b88"><div class="ttname"><a href="https://root.cern.ch/doc/master/classTCanvasImp.html#aa4b811931315b7f4852f0462ed9f9b88">TCanvasImp::ShowMenuBar</a></div><div class="ttdeci">virtual void ShowMenuBar(Bool_t show=kTRUE)</div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/TCanvasImp_8h_source.html#l00090">TCanvasImp.h:90</a></div></div>
<div class="ttc" id="classTCanvasImp_html_add4bb48191350eb01d1def0ef0de22a1"><div class="ttname"><a href="https://root.cern.ch/doc/master/classTCanvasImp.html#add4bb48191350eb01d1def0ef0de22a1">TCanvasImp::ForceUpdate</a></div><div class="ttdeci">virtual void ForceUpdate()</div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/TCanvasImp_8h_source.html#l00053">TCanvasImp.h:53</a></div></div>
<div class="ttc" id="classTCanvasImp_html_a2f839d49686cd9ad96865ea2f8a0f28f"><div class="ttname"><a href="https://root.cern.ch/doc/master/classTCanvasImp.html#a2f839d49686cd9ad96865ea2f8a0f28f">TCanvasImp::Iconify</a></div><div class="ttdeci">virtual void Iconify()</div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/TCanvasImp_8h_source.html#l00055">TCanvasImp.h:55</a></div></div>
<div class="ttc" id="RtypesCore_8h_html_a7c1bc4939263cb6c0f48e434d77ac258"><div class="ttname"><a href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a7c1bc4939263cb6c0f48e434d77ac258">UInt_t</a></div><div class="ttdeci">unsigned int UInt_t</div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/RtypesCore_8h_source.html#l00042">RtypesCore.h:42</a></div></div>
<div class="ttc" id="classTCanvasImp_html_a2c2d1a98a7573ec72056f3a18d4ad637"><div class="ttname"><a href="https://root.cern.ch/doc/master/classTCanvasImp.html#a2c2d1a98a7573ec72056f3a18d4ad637">TCanvasImp::HasMenuBar</a></div><div class="ttdeci">virtual Bool_t HasMenuBar() const </div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/TCanvasImp_8h_source.html#l00073">TCanvasImp.h:73</a></div></div>
<div class="ttc" id="classTCanvasImp_html_aaf6cd381c82450b274bc1f128a30e42d"><div class="ttname"><a href="https://root.cern.ch/doc/master/classTCanvasImp.html#aaf6cd381c82450b274bc1f128a30e42d">TCanvasImp::ShowStatusBar</a></div><div class="ttdeci">virtual void ShowStatusBar(Bool_t show=kTRUE)</div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/TCanvasImp_8h_source.html#l00091">TCanvasImp.h:91</a></div></div>
<div class="ttc" id="RtypesCore_8h_html_a7e568baf910535e8ffd438acb843434d"><div class="ttname"><a href="https://root.cern.ch/doc/master/RtypesCore_8h.html#a7e568baf910535e8ffd438acb843434d">kFALSE</a></div><div class="ttdeci">const Bool_t kFALSE</div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/RtypesCore_8h_source.html#l00098">RtypesCore.h:98</a></div></div>
<div class="ttc" id="classTCanvas_html"><div class="ttname"><a href="https://root.cern.ch/doc/master/classTCanvas.html">TCanvas</a></div><div class="ttdoc">The Canvas class. </div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/TCanvas_8h_source.html#l00031">TCanvas.h:31</a></div></div>
<div class="ttc" id="entrylist__figure1_8C_html_af575f17e6be3f269b86b041a60560dbf"><div class="ttname"><a href="https://root.cern.ch/doc/master/entrylist__figure1_8C.html#af575f17e6be3f269b86b041a60560dbf">text</a></div><div class="ttdeci">TText * text</div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/entrylist__figure1_8C_source.html#l00010">entrylist_figure1.C:10</a></div></div>
<div class="ttc" id="legend1_8C_html_a1380cd153a0fc78015dd604dbcb6c841"><div class="ttname"><a href="https://root.cern.ch/doc/master/legend1_8C.html#a1380cd153a0fc78015dd604dbcb6c841">y</a></div><div class="ttdeci">Double_t y[n]</div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/legend1_8C_source.html#l00017">legend1.C:17</a></div></div>
<div class="ttc" id="classTCanvasImp_html_aabffe435f4b676787a72c94b789e0171"><div class="ttname"><a href="https://root.cern.ch/doc/master/classTCanvasImp.html#aabffe435f4b676787a72c94b789e0171">TCanvasImp::SetWindowSize</a></div><div class="ttdeci">virtual void SetWindowSize(UInt_t w, UInt_t h)</div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/TCanvasImp_8h_source.html#l00087">TCanvasImp.h:87</a></div></div>
<div class="ttc" id="classTCanvasImp_html_af723c8c3eac62d92e8ba34bac80c24a9"><div class="ttname"><a href="https://root.cern.ch/doc/master/classTCanvasImp.html#af723c8c3eac62d92e8ba34bac80c24a9">TCanvasImp::Lock</a></div><div class="ttdeci">virtual void Lock()</div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/TCanvasImp_8h_source.html#l00041">TCanvasImp.h:41</a></div></div>
<div class="ttc" id="classTCanvasImp_html_ac486d4cbf5a0e8579e789ff674b8c17c"><div class="ttname"><a href="https://root.cern.ch/doc/master/classTCanvasImp.html#ac486d4cbf5a0e8579e789ff674b8c17c">TCanvasImp::ShowToolTips</a></div><div class="ttdeci">virtual void ShowToolTips(Bool_t show=kTRUE)</div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/TCanvasImp_8h_source.html#l00097">TCanvasImp.h:97</a></div></div>
<div class="ttc" id="classTCanvasImp_html_a3659d33f45cf47172045da9627c4cb3c"><div class="ttname"><a href="https://root.cern.ch/doc/master/classTCanvasImp.html#a3659d33f45cf47172045da9627c4cb3c">TCanvasImp::InitWindow</a></div><div class="ttdeci">virtual Int_t InitWindow()</div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/TCanvasImp_8h_source.html#l00056">TCanvasImp.h:56</a></div></div>
<div class="ttc" id="classTCanvasImp_html_ac7594eb595fe594d57468cfe441d3d78"><div class="ttname"><a href="https://root.cern.ch/doc/master/classTCanvasImp.html#ac7594eb595fe594d57468cfe441d3d78">TCanvasImp::GetWindowGeometry</a></div><div class="ttdeci">virtual UInt_t GetWindowGeometry(Int_t &amp;x, Int_t &amp;y, UInt_t &amp;w, UInt_t &amp;h)</div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/TCanvasImp_8h_source.html#l00083">TCanvasImp.h:83</a></div></div>
<div class="ttc" id="classTCanvasImp_html_ac6386a8dbe6a6abee94275219a01d30f"><div class="ttname"><a href="https://root.cern.ch/doc/master/classTCanvasImp.html#ac6386a8dbe6a6abee94275219a01d30f">TCanvasImp::SetStatusText</a></div><div class="ttdeci">virtual void SetStatusText(const char *text=0, Int_t partidx=0)</div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/TCanvasImp_8h_source.html#l00085">TCanvasImp.h:85</a></div></div>
<div class="ttc" id="classTCanvasImp_html_af79532f07f04b051aca8be6f3f08a096"><div class="ttname"><a href="https://root.cern.ch/doc/master/classTCanvasImp.html#af79532f07f04b051aca8be6f3f08a096">TCanvasImp::SetCanvasSize</a></div><div class="ttdeci">virtual void SetCanvasSize(UInt_t w, UInt_t h)</div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/TCanvasImp_8h_source.html#l00089">TCanvasImp.h:89</a></div></div>
<div class="ttc" id="classTCanvasImp_html_a51292b8e008acf04f882817c8ab7d779"><div class="ttname"><a href="https://root.cern.ch/doc/master/classTCanvasImp.html#a51292b8e008acf04f882817c8ab7d779">TCanvasImp::~TCanvasImp</a></div><div class="ttdeci">virtual ~TCanvasImp()</div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/TCanvasImp_8h_source.html#l00049">TCanvasImp.h:49</a></div></div>
<div class="ttc" id="RtypesCore_8h_html_af2f51d30ccd86e85be3e3e69793a86ef"><div class="ttname"><a href="https://root.cern.ch/doc/master/RtypesCore_8h.html#af2f51d30ccd86e85be3e3e69793a86ef">kTRUE</a></div><div class="ttdeci">const Bool_t kTRUE</div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/RtypesCore_8h_source.html#l00097">RtypesCore.h:97</a></div></div>
<div class="ttc" id="classTCanvasImp_html_aeb3e910019a0edc2fc127b70288095b0"><div class="ttname"><a href="https://root.cern.ch/doc/master/classTCanvasImp.html#aeb3e910019a0edc2fc127b70288095b0">TCanvasImp::Unlock</a></div><div class="ttdeci">virtual void Unlock()</div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/TCanvasImp_8h_source.html#l00042">TCanvasImp.h:42</a></div></div>
<div class="ttc" id="classTCanvasImp_html_a32c6c0fc7ae4c49366ecfbed6da59d09"><div class="ttname"><a href="https://root.cern.ch/doc/master/classTCanvasImp.html#a32c6c0fc7ae4c49366ecfbed6da59d09">TCanvasImp::fCanvas</a></div><div class="ttdeci">TCanvas * fCanvas</div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/TCanvasImp_8h_source.html#l00034">TCanvasImp.h:34</a></div></div>
<div class="ttc" id="TGX11_8cxx_html_a3777dbae63a15da001b2baa317a25149"><div class="ttname"><a href="https://root.cern.ch/doc/master/TGX11_8cxx.html#a3777dbae63a15da001b2baa317a25149">name</a></div><div class="ttdeci">char name[80]</div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/TGX11_8cxx_source.html#l00109">TGX11.cxx:109</a></div></div>
<div class="ttc" id="classTCanvasImp_html_aa7f976328703bf884f05e2e4698c1eac"><div class="ttname"><a href="https://root.cern.ch/doc/master/classTCanvasImp.html#aa7f976328703bf884f05e2e4698c1eac">TCanvasImp::HasToolTips</a></div><div class="ttdeci">virtual Bool_t HasToolTips() const </div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/TCanvasImp_8h_source.html#l00076">TCanvasImp.h:76</a></div></div>
</div><!-- fragment --></div><!-- contents -->


<div id="footer" style="background-color:#E5EBF3;">
<small>
<img class="footer" src="./TCanvasImp_files/rootlogo_s.gif" alt="root">
ROOT 6.09/03 - Reference Guide Generated on Tue Apr 11 2017 05:03:09 using Doxygen 1.8.9.
</small>
</div>


<div id="powerTip" class="s" style="top: 1359px; left: 599px; right: auto; bottom: auto; display: block;"><div class="ttname"><a href="https://root.cern.ch/doc/master/classTPad.html#a80aeefac6f7ee8ab3912945a51dd353f">TPad::fCanvas</a></div><div class="ttdeci">TCanvas * fCanvas</div><div class="ttdoc">! Pointer to mother canvas </div><div class="ttdef"><b>Definition:</b> <a href="https://root.cern.ch/doc/master/TPad_8h_source.html#l00105">TPad.h:105</a></div></div></body></html>